version: '2'
services:
  upload:
    build: .
    image: mantiser/upload:v2 
    volumes:
      - ./:/code
    #command: tail -f /etc/fstab
    environment:
      URL: "https://mantiser-com.ew.r.appspot.com/data/"
      KEY: "7B3PAFD2MEHHOcW3"
      NATS: nats
      MEILISEARCH: "http://meilisearch:7700"
    depends_on: 
      - nats
      - meilisearch
  #    - natin
  #natint:
  #  build: .
  #  command: python3 -u intoNats.py
  #  environment:
  #    NATS: nats
  #  depends_on: 
  #    - nats
  nats:
    image: nats

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700