apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-disk
  namespace: mantiser
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-cephfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    mantiser-com/user_id: "1112"
  name: finder-email
  labels:
    app: finder-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finder-email
  template:
    metadata:
      annotations:
        app: finder-email
      labels:
        app: finder-email
    spec:
      volumes:
        - name: files-disk
          persistentVolumeClaim:
            claimName: files-disk
      containers:
        - name: search
          volumeMounts:
            - name: files-disk
              mountPath: /files
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: MEILISEARCH 
              value: meilisearch.meilisearch.svc:7700
          resources:
            requests:
              cpu: 100m
              memory: 256Mi