#Mantiser upload 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantiser-uploader
  namespace: mantiser
spec:
  selector:
    matchLabels:
      app: mantiser-uploader
  template:
    metadata:
      labels:
        app: mantiser-uploader
    spec:
      containers:
        - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          name: mantiser-uploader
          imagePullPolicy: Always
          env:
            - name: NATS
              value: nats
            - name: SEARCH
              value: "Mantiser"
            - name: USER_ID
              value: "asdasdasdasd"
            - name: RESULT_NATS
              value: "nats"
            - name: MEILISEARCH 
              value: http://meilisearch.meilisearch.svc:7700
            - name: MUATIC_AUTH
              value: bWFudGlzZXI6bWFudGlzZXIxMjEy
            - name: MUATIC_URL
              value: https://mautic.apps.northamlin.com
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mantiser 
                  key: mongouri
                  optional: false

