apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantiser-uploader
spec:
  selector:
    matchLabels:
      app: mantiser-uploader
  template:
    metadata:
      labels:
        app: mantiser-uploader
    spec:
      containers:
        - image: mantiser/upload
          name: mantiser-uploader
          imagePullPolicy: Never
          env:
            - name: NATS
              value: nats.default.svc
            - name: SEARCH
              value: "Mantiser"
            - name: USER_ID
              value: "asdasdasdasd"
            - name: RESULT_NATS
              value: "nats"
            - name: MONGO_URI
              #value: mongodb://root:pass@mongodb.mantiser:27017
              value: "mongodb://root:aULF4AUQAT@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017/mantiser?authSource=admin&replicaSet=bd0"
          #command: ['python','-u','/code/service_watch.py']        
